import type { Lang } from "./i18n-types";

export type IndustryItem = {
  k: string;
  short: string;
  challenges: string[];
  solutions: string[];
  impact: string[];
  roi: string;
  image: string;
  featured: boolean;
  videoUrl?: string;
};

const en: IndustryItem[] = [
  { k: "Legal", short: "Contract intelligence, AI legal assistants and matter automation for firms and in-house teams.", challenges: ["Manual contract review", "Time-bound research", "Billable hour pressure"], solutions: ["AI Legal Assistant", "Contract intelligence", "Case research copilot"], impact: ["−70% drafting time", "+35% billable productivity"], roi: "3.8x in 9 months", image: "", featured: false },
  { k: "Construction", short: "Project intelligence, AI procurement and real-time variance control across sites.", challenges: ["Cost overruns", "Project visibility", "RFI bottlenecks"], solutions: ["AI project intelligence", "Automated reporting", "Procurement copilot"], impact: ["−18% project costs", "+25% on-time delivery"], roi: "4.2x in 12 months", image: "", featured: true },
  { k: "Real Estate", short: "AI lead qualification, virtual sales advisors and tenant servicing agents.", challenges: ["Slow lead follow-up", "Listing operations", "Tenant servicing"], solutions: ["AI Real Estate Assistant", "Lead nurturing agent", "Virtual sales advisor"], impact: ["+41% qualified leads", "−55% response time"], roi: "5.1x in 6 months", image: "", featured: true },
  { k: "E-commerce", short: "Conversion copilots, AI support and intelligent merchandising at scale.", challenges: ["Cart abandonment", "Support volume", "Personalization at scale"], solutions: ["AI Customer Support", "Conversion copilot", "Smart merchandising"], impact: ["+28% conversion", "−45% support cost"], roi: "6.4x in 6 months", image: "", featured: true },
  { k: "Healthcare", short: "Patient journey automation, documentation copilots and AI front-desk agents.", challenges: ["Scheduling load", "Patient comms", "Clinical documentation"], solutions: ["AI front-desk agent", "Documentation copilot", "Patient journey automation"], impact: ["−60% admin time", "+22 patient NPS"], roi: "3.5x in 9 months", image: "", featured: true },
  { k: "Call Center", short: "AR/EN voice agents, live-agent copilots and auto-QA across 100% of calls.", challenges: ["High AHT", "Agent turnover", "Quality assurance"], solutions: ["AI Call Center Agent", "Live agent assist", "Auto-QA"], impact: ["−42% AHT", "92% containment"], roi: "5.8x in 6 months", image: "", featured: false },
  { k: "Recruitment", short: "AI screening, conversational sourcing and end-to-end recruiter copilots.", challenges: ["CV overload", "Slow time-to-hire", "Candidate experience"], solutions: ["AI Recruitment Suite", "Smart screening", "Conversational sourcing"], impact: ["−63% time-to-hire", "+3x recruiter capacity"], roi: "4.7x in 6 months", image: "", featured: false },
  { k: "Content Creators", short: "Brand-locked AI content production across video, social, web and email.", challenges: ["Production bottlenecks", "Brand consistency", "Channel velocity"], solutions: ["Content Engine", "Multi-channel publishing", "Brand-locked AI"], impact: ["10x output", "−60% cost-per-asset"], roi: "8x in 4 months", image: "", featured: true },
  { k: "SMEs", short: "Lightweight AI ops bundles — sales, support, content and finance, in one.", challenges: ["Limited staff", "Fragmented tools", "Manual ops"], solutions: ["AI Ops Bundle", "Sales + support agents", "Lightweight ERP/CRM"], impact: ["+2x capacity", "−50% admin time"], roi: "4x in 6 months", image: "", featured: true },
  { k: "Restaurants", short: "AI ordering assistants, reservation management and demand-based inventory for restaurants and cafés.", challenges: ["Missed calls at peak hours", "Manual reservation handling", "Food waste from poor demand forecasting"], solutions: ["AI ordering & reservations agent", "WhatsApp ordering assistant", "Demand-based inventory planning"], impact: ["Fewer missed orders during rush hours", "Less food waste"], roi: "Payback typically within a few months", image: "", featured: false },
  { k: "Digital Marketing", short: "AI campaign optimization, content generation and lead-scoring for marketing agencies and in-house teams.", challenges: ["Manual campaign reporting", "Slow content production", "Unclear lead quality"], solutions: ["AI campaign analytics copilot", "Automated content generation", "AI lead scoring"], impact: ["Faster reporting cycles", "Higher-quality lead pipeline"], roi: "Varies by campaign scale", image: "", featured: false },
];

const ar: IndustryItem[] = [
  { k: "القانون", short: "ذكاء العقود، مساعدون قانونيون بالذكاء الاصطناعي، وأتمتة القضايا للمكاتب والإدارات القانونية.", challenges: ["مراجعة عقود يدوية", "بحث محدود بالوقت", "ضغط الساعات القابلة للفوترة"], solutions: ["مساعد قانوني بالذكاء الاصطناعي", "ذكاء العقود", "مساعد بحث قضائي"], impact: ["−70٪ زمن الصياغة", "+35٪ إنتاجية قابلة للفوترة"], roi: "3.8x خلال 9 أشهر", image: "", featured: false },
  { k: "المقاولات", short: "ذكاء المشاريع، مشتريات بالذكاء الاصطناعي، وضبط فوري للانحرافات في المواقع.", challenges: ["تجاوز التكاليف", "ضعف رؤية المشاريع", "اختناقات RFI"], solutions: ["ذكاء مشاريع", "تقارير آلية", "مساعد مشتريات"], impact: ["−18٪ تكاليف المشاريع", "+25٪ تسليم في الموعد"], roi: "4.2x خلال 12 شهراً", image: "", featured: true },
  { k: "العقار", short: "تأهيل الفرص بالذكاء الاصطناعي، مستشارو مبيعات افتراضيون، ووكلاء خدمة المستأجرين.", challenges: ["بطء متابعة الفرص", "عمليات الإعلانات", "خدمة المستأجرين"], solutions: ["مساعد عقاري بالذكاء الاصطناعي", "وكيل تنمية الفرص", "مستشار مبيعات افتراضي"], impact: ["+41٪ فرص مؤهلة", "−55٪ زمن الاستجابة"], roi: "5.1x خلال 6 أشهر", image: "", featured: true },
  { k: "التجارة الإلكترونية", short: "مساعدو تحويل، دعم بالذكاء الاصطناعي، وتسويق ذكي على نطاق واسع.", challenges: ["تخلي عن السلة", "حجم الدعم", "تخصيص على نطاق واسع"], solutions: ["دعم عملاء بالذكاء الاصطناعي", "مساعد تحويل", "تسويق ذكي"], impact: ["+28٪ معدل تحويل", "−45٪ تكلفة دعم"], roi: "6.4x خلال 6 أشهر", image: "", featured: true },
  { k: "الرعاية الصحية", short: "أتمتة رحلة المريض، مساعدو توثيق، ووكلاء استقبال بالذكاء الاصطناعي.", challenges: ["عبء الجدولة", "التواصل مع المرضى", "التوثيق السريري"], solutions: ["وكيل استقبال", "مساعد توثيق", "أتمتة رحلة المريض"], impact: ["−60٪ زمن إداري", "+22 NPS مرضى"], roi: "3.5x خلال 9 أشهر", image: "", featured: true },
  { k: "مراكز الاتصال", short: "وكلاء صوتيون عربي/إنجليزي، مساعدون مباشرون، وضبط جودة آلي لـ100٪ من المكالمات.", challenges: ["زمن معالجة مرتفع", "دوران الوكلاء", "ضمان الجودة"], solutions: ["وكيل مركز اتصال", "مساعد للوكيل المباشر", "ضبط جودة آلي"], impact: ["−42٪ AHT", "92٪ احتواء"], roi: "5.8x خلال 6 أشهر", image: "", featured: false },
  { k: "التوظيف", short: "فرز ذكي، تواصل تحادثي مع المرشحين، ومساعدون شاملون للمسؤول عن التوظيف.", challenges: ["تكدّس السير الذاتية", "بطء التوظيف", "تجربة المرشح"], solutions: ["مجموعة توظيف بالذكاء الاصطناعي", "فرز ذكي", "تواصل تحادثي"], impact: ["−63٪ زمن التوظيف", "+3x طاقة المسؤول"], roi: "4.7x خلال 6 أشهر", image: "", featured: false },
  { k: "صنّاع المحتوى", short: "إنتاج محتوى مقيّد بالهوية بالذكاء الاصطناعي عبر الفيديو والسوشيال والويب والبريد.", challenges: ["اختناقات الإنتاج", "اتساق الهوية", "سرعة القنوات"], solutions: ["محرك المحتوى", "نشر متعدد القنوات", "ذكاء اصطناعي مقيّد بالهوية"], impact: ["10x إنتاج", "−60٪ تكلفة لكل أصل"], roi: "8x خلال 4 أشهر", image: "", featured: true },
  { k: "المنشآت الصغيرة والمتوسطة", short: "حزم تشغيل خفيفة بالذكاء الاصطناعي — مبيعات ودعم ومحتوى ومالية في حزمة واحدة.", challenges: ["طاقم محدود", "أدوات متفرقة", "عمليات يدوية"], solutions: ["حزمة عمليات", "وكلاء مبيعات ودعم", "ERP/CRM خفيف"], impact: ["+2x طاقة استيعابية", "−50٪ زمن إداري"], roi: "4x خلال 6 أشهر", image: "", featured: true },
  { k: "المطاعم", short: "مساعدو طلبات بالذكاء الاصطناعي، إدارة حجوزات، وتخطيط مخزون مبني على الطلب الفعلي للمطاعم والمقاهي.", challenges: ["مكالمات فائتة وقت الذروة", "إدارة الحجوزات يدويًا", "هدر في الطعام بسبب توقع طلب غير دقيق"], solutions: ["وكيل طلبات وحجوزات بالذكاء الاصطناعي", "مساعد طلب عبر واتساب", "تخطيط مخزون مبني على الطلب"], impact: ["تقليل الطلبات الفائتة وقت الذروة", "تقليل هدر الطعام"], roi: "عائد الاستثمار يتحقق عادة خلال أشهر قليلة", image: "", featured: false },
  { k: "التسويق الإلكتروني", short: "تحسين الحملات بالذكاء الاصطناعي، توليد محتوى، وتقييم جودة العملاء المحتملين لوكالات ومسوقي الشركات.", challenges: ["تقارير حملات يدوية", "بطء إنتاج المحتوى", "عدم وضوح جودة العملاء المحتملين"], solutions: ["مساعد تحليلات حملات بالذكاء الاصطناعي", "توليد محتوى آلي", "تقييم ذكي للعملاء المحتملين"], impact: ["دورات تقارير أسرع", "جودة أعلى لقاعدة العملاء المحتملين"], roi: "يختلف حسب حجم الحملة", image: "", featured: false },
];

export const industryCatalog: Record<Lang, IndustryItem[]> = { en, ar };
